name: Tests on windows

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Install scoop
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          scoop update
          scoop checkup
          scoop install 7zip imagemagick ghostscript unrar
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        shell: powershell

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: zip, fileinfo, intl
          coverage: pcov

      # - name: Install rar extension
      #   run: |
      #     php -i | find "Thread Safety"
      #     php -i | grep "Architecture"
      #     Invoke-WebRequest -Uri https://windows.php.net/downloads/pecl/releases/rar/4.2.0/php_rar-4.2.0-8.1-nts-vs16-x64.zip -OutFile php_rar.zip
      #     7z x php_rar.zip -ophp_rar
      #     cd php_rar
      #     cp php_rar.dll C:\tools\php\ext\php_rar.dll
      #     Add-Content C:\tools\php\php.ini "`nextension=rar`n"
      #   shell: powershell

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      # - name: Check extension rar
      #   run: php -m | grep rar

      - name: Check extension imagick
        run: php -m | grep imagick

      - name: Execute tests
        run: vendor/bin/pest
